### ISSUE TITLE
Take a look at xonsh docs

### ISSUE THREAD

**Issue by anki-code** [shunk031/dotfiles#88]
Hi @shunk031! I just noticed that you tried xonsh.
I recommend to take a look into two repos:
* [xonsh-cheatsheet](https://github.com/anki-code/xonsh-cheatsheet/blob/main/README.md) - best start
* [xonsh-rc-awesome](https://github.com/anki-code/xontrib-rc-awesome/) - best example of RC file

**Comment by shunk031** [comment]
Thank you for telling me about it. I appreciate your comments and will close this issue.
